CREATE TABLE IF NOT EXISTS isocodes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(3) UNIQUE
);

CREATE TABLE IF NOT EXISTS counterparties (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  counterparty VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS legalentities (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  entity VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS styles (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  style VARCHAR(64) NOT NULL
);